app_name: bronze_ingestor
input:
  bootstrap_servers: broker1:29092,broker2:29092,broker3:29092
  topic: mooc.raw.events
  starting_offsets: latest
storage:
  table_path: s3a://lakehouse/mooc/bronze/mooc_events_raw
checkpoint:
  base_path: s3a://platform/mooc/bronze_ingestor
streaming:
  query_name: bronze_ingestor_raw
options:
  partition_by:
    - ingest_date
    - ingest_hour
