app_name: silver_transformer
input:
  bronze_table_path: s3a://lakehouse/mooc/bronze/mooc_events_raw
storage:
  learning_path: s3a://lakehouse/mooc/silver/learning_events
  performance_path: s3a://lakehouse/mooc/silver/performance_events
  exam_path: s3a://lakehouse/mooc/silver/exam_attempts
  video_path: s3a://lakehouse/mooc/silver/video_interactions
  navigation_path: s3a://lakehouse/mooc/silver/navigation_events
  pdf_path: s3a://lakehouse/mooc/silver/pdf_interactions
  system_path: s3a://lakehouse/mooc/silver/system_events
  unknown_path: s3a://lakehouse/mooc/silver/unknown_events
checkpoint:
  base_path: s3a://platform/mooc/silver_transformer
streaming:
  learning_query_name: silver_learning_events
  performance_query_name: silver_performance_events
  exam_query_name: silver_exam_attempts
  video_query_name: silver_video_interactions
  navigation_query_name: silver_navigation_events
  pdf_query_name: silver_pdf_interactions
  system_query_name: silver_system_events
  unknown_query_name: silver_unknown_events
