from pyspark.sql.types import BooleanType, DateType, DoubleType, LongType, StringType, StructField, StructType, TimestampType

EXAM_INTEGRITY_SIGNALS_SCHEMA = StructType(
    [
        StructField("event_date", DateType(), True),
        StructField("course_id", StringType(), True),
        StructField("exam_id", LongType(), True),
        StructField("exam_content_id", StringType(), True),
        StructField("exam_name", StringType(), True),
        StructField("attempt_id", LongType(), True),
        StructField("attempt_user_id", LongType(), True),
        StructField("user_id", LongType(), True),
        StructField("username", StringType(), True),
        StructField("time_limit_mins", LongType(), True),
        StructField("allowed_time_limit_mins", LongType(), True),
        StructField("exam_is_proctored", BooleanType(), True),
        StructField("exam_is_practice_exam", BooleanType(), True),
        StructField("exam_is_active", BooleanType(), True),
        StructField("attempt_started_at", TimestampType(), True),
        StructField("attempt_completed_at", TimestampType(), True),
        StructField("attempt_window_start", TimestampType(), True),
        StructField("attempt_window_end", TimestampType(), True),
        StructField("attempt_duration_secs", DoubleType(), True),
        StructField("event_count", LongType(), True),
        StructField("distinct_sessions", LongType(), True),
        StructField("distinct_exam_ips", LongType(), True),
        StructField("created_count", LongType(), True),
        StructField("started_count", LongType(), True),
        StructField("ready_to_submit_count", LongType(), True),
        StructField("submitted_count", LongType(), True),
        StructField("max_elapsed_time_secs", LongType(), True),
        StructField("security_event_count", LongType(), True),
        StructField("distinct_security_sessions", LongType(), True),
        StructField("distinct_login_ips", LongType(), True),
        StructField("login_event_count", LongType(), True),
        StructField("proctoring_event_count", LongType(), True),
        StructField("first_time", TimestampType(), True),
        StructField("last_time", TimestampType(), True),
        StructField("last_event_time", TimestampType(), True),
        StructField("rolling_mean_7", DoubleType(), True),
        StructField("rolling_std_7", DoubleType(), True),
        StructField("z_score", DoubleType(), True),
        StructField("is_anomaly", BooleanType(), True),
        StructField("anomaly_domain", StringType(), True),
        StructField("anomaly_type", StringType(), True),
        StructField("entity_type", StringType(), True),
        StructField("entity_id", StringType(), True),
        StructField("metric_name", StringType(), True),
        StructField("metric_value", DoubleType(), True),
    ]
)
