spark.sql.session.timeZone                        UTC
spark.serializer                                  org.apache.spark.serializer.KryoSerializer
spark.sql.adaptive.enabled                        true
spark.sql.shuffle.partitions                      32

spark.jars.packages                               io.delta:delta-spark_2.12:3.2.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
spark.jars.ivy                                    /opt/bitnami/spark/.ivy2
spark.sql.extensions                              io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog                   org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.databricks.delta.schema.autoMerge.enabled   true

spark.hadoop.fs.s3a.endpoint                      http://minio:9000
spark.hadoop.fs.s3a.path.style.access             true
spark.hadoop.fs.s3a.connection.ssl.enabled        false
spark.hadoop.fs.s3a.aws.credentials.provider      org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

spark.eventLog.enabled                            true
spark.eventLog.dir                                s3a://platform/spark-events/logs
spark.history.fs.logDirectory                     s3a://platform/spark-events/logs
spark.history.ui.port                             18080
spark.history.fs.update.interval                  10s

spark.executorEnv.PYTHONPATH                      /opt/project/spark
spark.executorEnv.PYSPARK_PYTHON                  /opt/bitnami/python/bin/python
spark.pyspark.python                              /opt/bitnami/python/bin/python
spark.pyspark.driver.python                       /opt/bitnami/python/bin/python
spark.driver.extraJavaOptions                     -Duser.timezone=UTC
spark.executor.extraJavaOptions                   -Duser.timezone=UTC
